cosy.resource.form = {}
cosy.resource.form.generator = {}
cosy.resource.form.generator.quantity = {}
cosy.resource.form.generator.quantity.hint = [[a positive integer]]
cosy.resource.form.generator.quantity.value = 2
cosy.resource.form.generator.quantity.type = [[text]]
cosy.resource.form.generator.quantity.name = [[# of dining philosophers?]]
cosy.resource.form.generator.close = {}
cosy.resource.form.generator.close.clicked = false
cosy.resource.form.generator.close.type = [[button]]
cosy.resource.form.generator.close.is_active = true
cosy.resource.form.generator.close.name = [[Close]]
cosy.resource.form.generator.generate = {}
cosy.resource.form.generator.generate.clicked = false
cosy.resource.form.generator.generate.type = [[button]]
cosy.resource.form.generator.generate.is_active = false
cosy.resource.form.generator.generate.name = [[Generate!]]
cosy.resource.form.generator.name = [[Generator]]
cosy.resource.form.generator.type = [[form]]
cosy.resource.think = {}
cosy.resource.wait = {}
cosy.resource.eat = {}
cosy.resource.fork = {}
cosy.resource.left = {}
cosy.resource.right = {}
cosy.resource.release = {}
cosy.resource.arcs = {}
cosy.resource.number = 0
cosy.resource.number = 1
cosy.resource.think[1] = {}
cosy.resource.think[1].position = [[400:360]]
cosy.resource.think[1].type = [[place]]
cosy.resource.think[1].marking = true
cosy.resource.think[1].name = [[Averroës is thinking]]
cosy.resource.wait[1] = {}
cosy.resource.wait[1].position = [[200:360]]
cosy.resource.wait[1].type = [[place]]
cosy.resource.wait[1].marking = false
cosy.resource.wait[1].name = [[Averroës is waiting]]
cosy.resource.eat[1] = {}
cosy.resource.eat[1].position = [[100:360]]
cosy.resource.eat[1].type = [[place]]
cosy.resource.eat[1].marking = false
cosy.resource.eat[1].name = [[Averroës is eating]]
cosy.resource.fork[1] = {}
cosy.resource.fork[1].position = [[300:540]]
cosy.resource.fork[1].type = [[place]]
cosy.resource.fork[1].marking = true
cosy.resource.fork[1].name = [[Averroës's fork]]
cosy.resource.left[1] = {}
cosy.resource.left[1].position = [[350:360]]
cosy.resource.left[1].name = [[Averroës takes his fork]]
cosy.resource.left[1].type = [[transition]]
cosy.resource.right[1] = {}
cosy.resource.right[1].position = [[150:360]]
cosy.resource.right[1].name = [[Averroës takes Averroës's fork]]
cosy.resource.right[1].type = [[transition]]
cosy.resource.release[1] = {}
cosy.resource.release[1].position = [[050:360]]
cosy.resource.release[1].name = [[Averroës releases forks]]
cosy.resource.release[1].type = [[transition]]
cosy.resource.arcs[1] = {}
cosy.resource.arcs[1].think_left = {}
cosy.resource.arcs[1].think_left.source = cosy.resource.think[1]
cosy.resource.arcs[1].think_left.target = cosy.resource.left[1]
cosy.resource.arcs[1].think_left.type = [[arc]]
cosy.resource.arcs[1].fork_left = {}
cosy.resource.arcs[1].fork_left.source = cosy.resource.fork[1]
cosy.resource.arcs[1].fork_left.target = cosy.resource.arcs[1].think_left.target
cosy.resource.arcs[1].fork_left.type = [[arc]]
cosy.resource.arcs[1].left_wait = {}
cosy.resource.arcs[1].left_wait.source = cosy.resource.arcs[1].fork_left.target
cosy.resource.arcs[1].left_wait.target = cosy.resource.wait[1]
cosy.resource.arcs[1].left_wait.type = [[arc]]
cosy.resource.arcs[1].wait_right = {}
cosy.resource.arcs[1].wait_right.source = cosy.resource.wait[1]
cosy.resource.arcs[1].wait_right.target = cosy.resource.right[1]
cosy.resource.arcs[1].wait_right.type = [[arc]]
cosy.resource.arcs[1].right_eat = {}
cosy.resource.arcs[1].right_eat.source = cosy.resource.arcs[1].wait_right.target
cosy.resource.arcs[1].right_eat.target = cosy.resource.eat[1]
cosy.resource.arcs[1].right_eat.type = [[arc]]
cosy.resource.arcs[1].eat_release = {}
cosy.resource.arcs[1].eat_release.source = cosy.resource.eat[1]
cosy.resource.arcs[1].eat_release.target = cosy.resource.release[1]
cosy.resource.arcs[1].eat_release.type = [[arc]]
cosy.resource.arcs[1].release_think = {}
cosy.resource.arcs[1].release_think.source = cosy.resource.release[1]
cosy.resource.arcs[1].release_think.target = cosy.resource.think[1]
cosy.resource.arcs[1].release_think.type = [[arc]]
cosy.resource.arcs[1].release_fork_1 = {}
cosy.resource.arcs[1].release_fork_1.source = cosy.resource.release[1]
cosy.resource.arcs[1].release_fork_1.target = cosy.resource.fork[1]
cosy.resource.arcs[1].release_fork_1.type = [[arc]]
cosy.resource.number = 2
cosy.resource.think[1].position = [[400:180]]
cosy.resource.arcs[1].wait_right.source.position = [[200:180]]
cosy.resource.eat[1].position = [[100:180]]
cosy.resource.fork[1].position = [[300:270]]
cosy.resource.arcs[1].fork_left.target.position = [[355:180]]
cosy.resource.arcs[1].wait_right.target.position = [[150:180]]
cosy.resource.release[1].position = [[050:180]]
cosy.resource.think[2] = {}
cosy.resource.think[2].position = [[400:360]]
cosy.resource.think[2].type = [[place]]
cosy.resource.think[2].marking = true
cosy.resource.think[2].name = [[C.S. Peirce is thinking]]
cosy.resource.wait[2] = {}
cosy.resource.wait[2].position = [[-200,-150]]
cosy.resource.wait[2].type = [[place]]
cosy.resource.wait[2].marking = false
cosy.resource.wait[2].name = [[C.S. Peirce is waiting]]
cosy.resource.eat[2] = {}
cosy.resource.eat[2].position = [[100:360]]
cosy.resource.eat[2].type = [[place]]
cosy.resource.eat[2].marking = false
cosy.resource.eat[2].name = [[C.S. Peirce is eating]]
cosy.resource.fork[2] = {}
cosy.resource.fork[2].position = [[200,200]]
cosy.resource.fork[2].highlighted = true
cosy.resource.fork[2].type = [[place]]
cosy.resource.fork[2].marking = true
cosy.resource.fork[2].name = [[C.S. Peirce's fork]]
cosy.resource.left[2] = {}
cosy.resource.left[2].position = [[350:360]]
cosy.resource.left[2].name = [[C.S. Peirce takes his fork]]
cosy.resource.left[2].type = [[transition]]
cosy.resource.arcs[1].wait_right.target.name = [[Averroës takes C.S. Peirce's fork]]
cosy.resource.right[2] = {}
cosy.resource.right[2].position = [[150, 240]]
cosy.resource.right[2].name = [[C.S. Peirce takes Averroës's fork]]
cosy.resource.right[2].type = [[transition]]
cosy.resource.release[2] = {}
cosy.resource.release[2].position = [[050:360]]
cosy.resource.release[2].name = [[C.S. Peirce releases forks]]
cosy.resource.release[2].type = [[transition]]
cosy.resource.arcs[2] = {}
cosy.resource.arcs[2].think_left = {}
cosy.resource.arcs[2].think_left.source = cosy.resource.think[2]
cosy.resource.arcs[2].think_left.target = cosy.resource.left[2]
cosy.resource.arcs[2].think_left.type = [[arc]]
cosy.resource.arcs[2].fork_left = {}
cosy.resource.arcs[2].fork_left.source = cosy.resource.fork[2]
cosy.resource.arcs[2].fork_left.target = cosy.resource.left[2]
cosy.resource.arcs[2].fork_left.type = [[arc]]
cosy.resource.arcs[2].left_wait = {}
cosy.resource.arcs[2].left_wait.source = cosy.resource.arcs[2].fork_left.target
cosy.resource.arcs[2].left_wait.target = cosy.resource.wait[2]
cosy.resource.arcs[2].left_wait.type = [[arc]]
cosy.resource.arcs[2].wait_right = {}
cosy.resource.arcs[2].wait_right.source = cosy.resource.wait[2]
cosy.resource.arcs[2].wait_right.target = cosy.resource.right[2]
cosy.resource.arcs[2].wait_right.type = [[arc]]
cosy.resource.arcs[2].right_eat = {}
cosy.resource.arcs[2].right_eat.source = cosy.resource.arcs[2].wait_right.target
cosy.resource.arcs[2].right_eat.target = cosy.resource.eat[2]
cosy.resource.arcs[2].right_eat.type = [[arc]]
cosy.resource.arcs[2].eat_release = {}
cosy.resource.arcs[2].eat_release.source = cosy.resource.eat[2]
cosy.resource.arcs[2].eat_release.target = cosy.resource.release[2]
cosy.resource.arcs[2].eat_release.type = [[arc]]
cosy.resource.arcs[2].release_think = {}
cosy.resource.arcs[2].release_think.source = cosy.resource.arcs[2].eat_release.target
cosy.resource.arcs[2].release_think.target = cosy.resource.think[2]
cosy.resource.arcs[2].release_think.type = [[arc]]
cosy.resource.arcs[2].release_fork_1 = {}
cosy.resource.arcs[2].release_fork_1.source = cosy.resource.arcs[2].release_think.source
cosy.resource.arcs[2].release_fork_1.target = cosy.resource.fork[2]
cosy.resource.arcs[2].release_fork_1.lock_pos = true
cosy.resource.arcs[2].release_fork_1.type = [[arc]]
cosy.resource.arcs[1].fork_right = {}
cosy.resource.arcs[1].fork_right.source = cosy.resource.fork[2]
cosy.resource.arcs[1].fork_right.target = cosy.resource.arcs[1].wait_right.target
cosy.resource.arcs[1].fork_right.type = [[arc]]
cosy.resource.arcs[2].fork_right = {}
cosy.resource.arcs[2].fork_right.source = cosy.resource.fork[1]
cosy.resource.arcs[2].fork_right.target = cosy.resource.arcs[2].right_eat.source
cosy.resource.arcs[2].fork_right.type = [[arc]]
cosy.resource.arcs[1].release_fork_2 = {}
cosy.resource.arcs[1].release_fork_2.source = cosy.resource.arcs[1].release_fork_1.source
cosy.resource.arcs[1].release_fork_2.target = cosy.resource.arcs[1].fork_right.source
cosy.resource.arcs[1].release_fork_2.type = [[arc]]
cosy.resource.arcs[2].release_fork_2 = {}
cosy.resource.arcs[2].release_fork_2.source = cosy.resource.arcs[2].release_fork_1.source
cosy.resource.arcs[2].release_fork_2.target = cosy.resource.arcs[1].release_fork_1.target
cosy.resource.arcs[2].release_fork_2.type = [[arc]]
